In [9]:
import numpy as np

#### Problem Statement 1: 
 Write a function so that the columns of the output matrix are powers of the input vector. 
 The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
 HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [5]:
def vander(arr, N, increasing):
    import numpy as np
    length = len(arr)
    arr = np.array(arr).reshape(length, 1)
    result = np.zeros((length, N), dtype='int64')
    result = result + arr
    power = []
    for i in range(N):
        power.append(N-i-1)
    if increasing:
        power = list(reversed(power))
    power = np.array(power)
    result = result ** power
    return result

In [6]:
arr = [1,2,3,4]

print(vander(arr, 4, True))




[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


#### Problem Statement 2: 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
i 1 2 3 4 5 6 7 8 9 10 
===== == == == == == == == == == == 
Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4 
y2 35 = (20+30+40+50)/4 
y3 45 = (30+40+50+60)/4 
y4 55 = (40+50+60+70)/4 
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 


Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [38]:
def moving_avarages(a,k):
    p = len(a)-k+1
    for i in range(p):
        print(f'y{i+1}:',np.mean(a[:k]))
        del a[0]
    

In [39]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [40]:
moving_avarages(a,3)

y1: 5.0
y2: 4.666666666666667
y3: 5.666666666666667
y4: 6.666666666666667
y5: 9.666666666666666
y6: 28.666666666666668
y7: 49.333333333333336
y8: 72.66666666666667
y9: 84.0
y10: 93.33333333333333
y11: 116.33333333333333
